kind: Service
apiVersion: v1
metadata:
  name: pentaho-server-ce-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pentaho-server-ce
  ports:
  - name: http
    port: 80
    targetPort: 8080
