apiVersion: extensions/v1beta2
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels: &PostgreSQLLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgresql-server
spec:
  replicas: 1
  selector:
    matchLabels: *PostgreSQLLabels
  serviceName: {{ .Release.Name }}-postgresql-svc
  template:
    metadata:
      labels: *PostgreSQLLabels
    spec: 
      containers:
        - name: postgresql-server
          image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - containerPort: 5432
              name: postgres
 	  volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: {{ .Release.Name }}-postgresql-pvc	
          env:
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.postgresql.pass }}
          resources:
            requests:
              cpu: 500m
              memory: 0.5Gi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
      - name: sonatype-nexus-data
        persistentVolumeClaim:
          claimName: nexus-data-pv-claim
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-postgresql-pvc
      labels: *PostgreSQLLabels
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: {{ .Values.postgresql.volumeSize }}Gi
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-postgresql-svc
  labels: &PostgreSQLLabels
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: postgresql-server
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector: *PostgreSQLLabels
{{ if .Values.postgresql.exposePublicService }}
  type: LoadBalancer
{{ else }}
  type: ClusterIP
{{ end }}
---
