apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pentaho-server-ce-tls-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx    
spec:
  rules:
  - host: pentaho.krugernetes.com
    http:
      paths:
      - backend:
          serviceName: pentaho-server-ce-svc
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - pentaho.krugernetes.com